### ISSUE TITLE
Tools for testing both sides of optionally generated function?

### ISSUE THREAD

**Issue by oxinabox** [JuliaTesting/PerformanceTestTools.jl#7]
Not sure if on topic here,
but the way to test both sides of an optional generate function is very similar to what seems to be done in the source of this package.
One needs to rerun those tests both with and without `--compile=min` flag

https://stackoverflow.com/questions/58612962/how-do-i-test-both-sides-of-a-if-generated#comment103536216_58612962

**Comment by tkf** [comment]
Interesting. I didn't know that's how you test the both sides. Yes, I think it makes sense to add it here.

I also want to have a convenient way to run tests with and without threading. Perhaps it can be covered with some shared internal logic.
